# Generated by Django 3.2.5 on 2021-08-09 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20210809_2111'),
    ]

    operations = [
        migrations.AddField(
            model_name='mom',
            name='slug',
            field=models.CharField(default=0, max_length=3),
            preserve_default=False,
        ),
    ]
