# Generated by Django 3.2.5 on 2021-08-09 18:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_remove_mom_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mom',
            name='time',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
