# Generated by Django 3.2.5 on 2021-08-09 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_mom_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mom',
            old_name='time',
            new_name='date',
        ),
    ]
