# Generated by Django 3.2.5 on 2021-08-09 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_rename_time_mom_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mom',
            old_name='date',
            new_name='time',
        ),
    ]
