# Generated by Django 3.2.5 on 2021-08-09 18:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_mom_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mom',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
