# Generated by Django 3.2.5 on 2021-08-09 18:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_alter_mom_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='mom',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
